### ISSUE TITLE
How can I configure my Varnish Server 

### ISSUE THREAD

**Issue by p-graeser** [mittwald/typo3-varnishcache#10]
I hope you can help me.

I've installed your extension and included the static typoscript settings, but what to do next? In your Documentation you mentioned a picture with the Varnish Server Configuration, but where I find these section? The only thing I found is the option to disable caching for a specific Content Element.

**Comment by p-graeser** [comment]
I found the mistake.
Your last commit is not present in the Version you over via the TYPO3 Extension-Repository. Please correct that.

Best regards 
Patrick Gräser

**Comment by pstranghoener** [comment]
We know that commit is not in the TER, because we want to develop more fetaures. You can use the development branch or put the Varnish Server Configuration on a Folder.
