### ISSUE TITLE
Page is being generated.

### ISSUE THREAD

**Issue by andrebardoun** [mittwald/typo3-varnishcache#16]
Hi there,

I get the message "Page is being generated. If this message does not disappear within 30 seconds, please reload." when varnishcache extension is active.

On pages with this message are own plugins. Do I have respect something about caching if I use varnishcache?

Using 1.0.3 from TER and TYPO3 7.6.14

**Comment by Hermsi1337** [comment]
Hey,

what kind of "own plugins" are you using? 
Have you already tried to exclude them with ESI-Tags? ( Page > Edit Content Module > caching )

If ESI-Tags don't do the trick, try to exclude the URL via Varnish VCL, just to check if the "Page is being generated"-Page persists.

Regards

**Comment by Littlebudder** [comment]
This plugin show tx_news records as issue/ article-archive.

I have already triet to exclude them with ESI-Tags - problem still exists.

When I exclude the URL via Varnish VCL the message still exists.

The "Page is being..."-Message is not over the complete site. Only single content-elements/ plugins seem to be not renderd.

**Comment by Hermsi1337** [comment]
Without links or access to your website it's quite difficult to analyse this one.
Is it possible to ask your hoster for help?

**Comment by ifx-cw** [comment]
I happen to know that this:
[https://github.com/mittwald/typo3-varnishcache/issues/9#issuecomment-276662350](https://github.com/mittwald/typo3-varnishcache/issues/9#issuecomment-276662350)

was the cause for that error also.

**Comment by christophlehmann** [comment]
The message appears, when multiple request would render the same page which is actually not in the cache. Basically it's a DOS-prevention and **not** a problem with the varnish extension. You can disable the message with adapting `$TYPO3_CONF_VARS['SYS']['lockingMode']`.
