### ISSUE TITLE
Table tx_varnishcache_domain_model_sysdomain doesn't exist

### ISSUE THREAD

**Issue by reiherm** [mittwald/typo3-varnishcache#3]
While creating an new varnish server configuration record i get the following exception:

> Uncaught TYPO3 Exception
> #1247602160: Table 'usr_pXXXXXX_1.tx_varnishcache_domain_model_sysdomain' doesn't exist

It seems to be that there is no tx_varnishcache_domain_model_sysdomain table in the ext_tables.sql file?

**Comment by kpurrmann** [comment]
You have to include static typoscript.
